### PR TITLE
Add a Resetable RegisterFile to stdlib basic rtl

### PR DESCRIPTION
**Pull request by jbrzozo24**
Needed for fixing ECE5745 blocking cache for use in 4 state simulation

### CODE REVIEW

**Comment by ptpan** [comment]
The implementation looks good to me. My concern is that `stdlib.basic_rtl` has always been a set of synthesizable components, and `RegisterFileRst` is not one of them. Maybe you can move your implementation of `RegisterFileRst` to a new file under `stdlib.mem` (not all memories in that directory are synthesizable)? And also add a comment to the class saying this is just modeling and not for synthesis?

**Comment by cbatten** [comment]
But it is supposed to be for synthesis?

**Comment by ptpan** [comment]
> But it is supposed to be for synthesis?

I mean you cannot easily swap in an SRAM bank for `RegisterFileRst` as you can do for `RegisterFile`. That's why `RegsiterFile` is under `basic_rtl` and also why I wanted to keep `RegisterFileRst` separate from `basic_rtl`.

**Comment by cbatten** [comment]
You cannot swap a SRAM bank in for RegisterFile because a register file is combinational read ... I think RegisterFileRst should go in `basic_rtl` since it is a simple synthesizable component ... it is kind of completely separate from SRAMs?

**Comment by ptpan** [comment]
> You cannot swap a SRAM bank in for RegisterFile because a register file is combinational read ... I think RegisterFileRst should go in `basic_rtl` since it is a simple synthesizable component ... it is kind of completely separate from SRAMs?

You are right.. I was thinking of register files implemented as SRAMs but rather `stdlib.basic_rtl.RegisterFile` is cleraly an array of registers.. Yeah it should go to basic_rtl then.

**Review by ptpan — APPROVED** [review]
Looks good to me

**Comment by ptpan** [comment]
@jbrzozo24 As per our convention, you will be the person to hit the "merge" button once a PR is approved... I'll make another minor release after these commits go into master.

**Comment by jbrzozo24** [comment]
I don't believe I have write access to this repo?

**Comment by ptpan** [comment]
> I don't believe I have write access to this repo?

Oops.. I was too used to that convention when almost all PRs come from the core pymtl3 devlopement team. It's nice to have your contribution to the repo!

**Pull request merged**
